export type { SPSlidesOptions, SlideData, Navigation, PresenterState, Transformer } from './types'

export { createSlidesPurryst } from './core'
export { exportStandalone } from './export'
export { spApi } from './sp-api'

export { useScale } from './composables/useScale'
export { useElementScale } from './composables/useElementScale'
export { useSteps, buildSteps, processHtml } from './composables/useSteps'
export { useNavigation } from './composables/useNavigation'
export { useSlides, parseElementToSlides } from './composables/useSlides'
export { usePresenter } from './composables/usePresenter'
export { useStorage, resetConfig } from './composables/useStorage'
export type { SpStorageConfig } from './composables/useStorage'
export { useSlideTree } from './composables/useSlideTree'
export type { TocItem } from './composables/useSlideTree'

export { default as SpPresentation } from './components/SpPresentation.vue'
export { default as SpSlide } from './components/SpSlide.vue'
export { default as SpAlternatives } from './components/SpAlternatives.vue'
export { default as SpAnim } from './components/SpAnim.vue'
export { default as SpDrag } from './components/SpDrag.vue'
export { default as SpImg } from './components/SpImg.vue'
export { default as SpInclude } from './components/SpInclude.vue'
export { default as SpSvg } from './components/SpSvg.vue'
export { default as SpStyle } from './components/SpStyle.vue'
export { default as SpToc } from './components/SpToc.vue'

export * from './transformers/svg'